###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "username": "Kirya",
    "email": "yasv@mail.ru",
    "password": "t,fnmgfhjkm",
    "first_name": "Kira",
    "last_name": "Yasnov",
    "is_staff": "True"
}

###
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f

###
GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f

###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token a238faaa6250176d932db8eb8b55c9db4e6b529f

{
    "new_password": "t,fnmgfhjkm",
    "current_password": "t,fnmgfhjkm1"
}

###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "yasv@mail.ru",
    "password": "t,fnmgfhjkm"
}

###
GET http://127.0.0.1:8000/api/tags/3/
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f

{
    "ingredients": [
        {
            "id": 1111,
            "amount": 56
        },
        {
            "id": 12,
            "amount": 30
        }
    ],
    "tags": [
        1,
        2
    ],
    "title": "Something2",
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "description": "Some text2",
    "cooking_time": 10
}

###
GET http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f

###
POST http://127.0.0.1:8000/api/recipes/1/favorite/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f

###
POST http://127.0.0.1:8000/api/users/1/subscribe/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f

###
DELETE http://127.0.0.1:8000/api/users/1/subscribe/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f

###
GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f


###
GET http://127.0.0.1:8000/api/ingredients/666/
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/recipes/5/shopping_cart/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f

###
DELETE http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f

###
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Content-Type: application/json
Authorization: Token 974157deae3af043576dd14f0d86e38a20bafc5f