version: '3.3'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: 'foodgram'
      POSTGRES_USER: 'foodgram_admin'
      POSTGRES_PASSWORD: 'wjbdcijwbd1kjn2'
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  frontend:
    image: cyalater/foodgram_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - postgres

  backend:
    image: cyalater/foodgram_backend:v1
    restart: always
    volumes:
      - static_value:/backend/foodgram/static/
      - media_value:/backend/foodgram/media/
    depends_on:
      - postgres
    env_file:
      - ./.env


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend

volumes:
  db:
  static_value:
  media_value: