# Generated by Django 4.1.1 on 2022-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='food_app.RecipeIngredients', to='food_app.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
