# Generated by Django 4.1.1 on 2022-10-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
    ]
